feat(python-stack): Add route generating vegetation difference in an area
ArchangelX360/EnvironmentalDisasterGoggles pull request #13
Opened 2016-12-09 17:10 UTC by FunkySayu

Implements a route in the Flask API, /forestDiff, getting the vegetation difference between two years in an area. This will return an RGB image where red stands for deforestation between the two years, green stands for reforestation, and blue is an unapplicable part of the image (such as river, ocean...)

2016-12-09 18:56 UTC, FunkySayu commented
TODO fix on this branch the delta time that does not support months < 1 for example.

2016-12-10 14:19 UTC, ArchangelX360 commented on computation/imagefetcher/imagefetcher/fetcher.py
> +                greater or equal than 2000.
Typo: must be greater **than** or equal **to**.

2016-12-10 14:21 UTC, ArchangelX360 commented on computation/imagefetcher/imagefetcher/app.py
> +            Must be greater than start year, and lower than 2016.
Hardcoded 2016 seems a bit weird, why didn't you use a "current year" instead?

2016-12-10 14:21 UTC, ArchangelX360 commented on computation/imagefetcher/imagefetcher/fetcher.py
> +                start_year, and lesser or equal to 2016.
Same comment about 2016.

2016-12-10 14:26 UTC, ArchangelX360 requested changes
Need explanation about this hardcoded 2016.

2016-12-10 14:33 UTC, FunkySayu commented on computation/imagefetcher/imagefetcher/fetcher.py
> +                greater or equal than 2000.
Done.

2016-12-10 14:33 UTC, FunkySayu commented on computation/imagefetcher/imagefetcher/fetcher.py
> +                start_year, and lesser or equal to 2016.
Done.

2016-12-10 14:36 UTC, ArchangelX360 approved these changes

2016-12-10 14:37 UTC, ArchangelX360 commented
LGTM.

2016-12-10 14:37 UTC, merged