feat(image-fetcher): Reformat parameters for flask server
ArchangelX360/EnvironmentalDisasterGoggles pull request #16
Opened 2016-12-10 16:05 UTC by cassand

2016-12-10 19:39 UTC, ArchangelX360 requested changes

2016-12-10 19:39 UTC, ArchangelX360 commented on backend/app/modules/imagefetcher/FetcherActor.scala
> +      if (message.scale.isDefined) initialParams :+ ("scale", message.scale.get.toInt.toString)
Python API match float also now

2016-12-10 19:39 UTC, ArchangelX360 commented on backend/app/modules/imagefetcher/FetcherActor.scala
> +    val currenSender = sender
Current not curren :)

2016-12-12 11:52 UTC, FunkySayu commented on backend/app/modules/imagefetcher/FetcherActor.scala
> +    val currentSender = sender
I don't get this change. Is there a scope issue?

2016-12-12 14:54 UTC, cassand commented on backend/app/modules/imagefetcher/FetcherActor.scala
> +    val currentSender = sender
Yes, sender refer to the sender of the last message receive by the actor, therefore, access it from a future can lead to an error (access to the sender of the next message instead)

2016-12-13 09:50 UTC, bouillonpi submitted a review, later dismissed

2016-12-13 14:48 UTC, merged