feat(python-stack): support query by country (additionally to polygon)
ArchangelX360/EnvironmentalDisasterGoggles pull request #22
Opened 2016-12-12 14:14 UTC by FunkySayu

Also change the default scale to 500 to ensure images are not too big.

2016-12-12 20:49 UTC, ArchangelX360 requested changes

2016-12-12 20:49 UTC, ArchangelX360 commented on computation/imagefetcher/imagefetcher/app.py
> +    if country is None and polygon is None:
Could you make this code more generic as it is duplicated?

2016-12-13 15:21 UTC, FunkySayu commented
Done.

2016-12-13 15:31 UTC, ArchangelX360 approved these changes

2016-12-13 15:45 UTC, merged