feat(nlp): Add Stanford parser to extract dates and link it with actors system
ArchangelX360/EnvironmentalDisasterGoggles pull request #23
Opened 2016-12-12 17:37 UTC by cassand

2016-12-12 20:47 UTC, ArchangelX360 commented on backend/app/modules/searchengine/SearchActor.scala
> +      place = "Pau",
State that "Pau" and "Fire" values are placeholders.

2016-12-12 20:47 UTC, ArchangelX360 requested changes
Placeholders need to be stated as is.

2016-12-13 15:30 UTC, ArchangelX360 approved these changes

2016-12-13 15:30 UTC, bouillonpi approved these changes

2016-12-13 15:30 UTC, merged