Feature/download image
ArchangelX360/EnvironmentalDisasterGoggles pull request #33
Opened 2016-12-23 15:17 UTC by cassand

2016-12-23 19:36 UTC, FunkySayu commented on backend/app/modules/imagefetcher/FetcherActor.scala
> +    * Download a file from an url through an akka stream an place it in the downloaded folder
s/an place/and place/g

2016-12-23 19:36 UTC, FunkySayu commented on backend/app/modules/imagefetcher/FetcherActor.scala
> +    * (Downloaded file is not labeled yet e.g random name)
s/ e.g random name/; we use a random id/g

2016-12-23 19:36 UTC, FunkySayu commented on backend/app/modules/imagefetcher/FetcherActor.scala
> +  def downloadFile(url: String, processId: String) = {
undocumented parameters

2016-12-23 19:36 UTC, FunkySayu commented on backend/app/modules/imagefetcher/FetcherActor.scala
> +
remove useless blank line

2016-12-23 19:36 UTC, FunkySayu commented on backend/app/modules/imagefetcher/FetcherActor.scala
> +      task.map(t => monitoring ! UpdateTask(processId, t.id, Some("Download started"), Some(20)))
`Some(20)` ? Why 20 ? From where ?

2016-12-23 19:36 UTC, FunkySayu commented on backend/app/modules/imagefetcher/FetcherActor.scala
> +    * (Downloaded file is not labeled yet e.g random name)
By the way, you may want to use the route parameter of the image to store the picture. Two generation of the same picture will generate the same route as much as I tested.

2016-12-23 19:36 UTC, FunkySayu commented on backend/app/modules/scheduler/SchedulerActor.scala
>      * * Download image
Double stars on the comments (I think you should use full english sentence to explain what does the pipeline); id parameter is not documented

2016-12-23 19:36 UTC, FunkySayu commented on backend/app/modules/scheduler/SchedulerActor.scala
> +      val details = monitoring
`details` is a bit obscure here. What is it? Process details? if so, use `process_details`. Or is it download details ? if so, use `download_details`.

2016-12-23 19:36 UTC, FunkySayu commented on backend/app/modules/scheduler/SchedulerActor.scala
> +        .flatMap(details => fetcherActor.ask(FetchRGB("2015-01-01", details.place, Some(100), id)))
Is scale required here (`Some(100)`)? Shouldn't we use the default scale?

2016-12-23 19:36 UTC, FunkySayu commented on backend/app/modules/scheduler/SchedulerActor.scala
> +      url.foreach(u => println(u.url))
A bit odd to see `url.foreach`. What is this? A list of URLs? Add a `s` after `url` then.

2016-12-23 19:36 UTC, FunkySayu commented on backend/app/modules/scheduler/SchedulerActor.scala
> +      url.foreach(u => println(u.url))
Also mark this as debug (`TODO(xxx): This is for debug purpose`)

2016-12-23 19:36 UTC, FunkySayu commented on backend/app/modules/scheduler/SchedulerActor.scala
> +      file foreach (downloaded => println(downloaded.file.getAbsolutePath))
Same here, mark this as debug.

2016-12-23 19:44 UTC, FunkySayu commented on backend/app/modules/imagefetcher/ZipUtil.scala
> +
remove blank line

2016-12-23 19:44 UTC, FunkySayu commented on backend/app/modules/imagefetcher/ZipUtil.scala
> +
remove blank line

2016-12-23 19:44 UTC, FunkySayu commented on backend/app/modules/imagefetcher/ZipUtil.scala
> +
remove blank line

2016-12-23 19:44 UTC, FunkySayu commented on backend/app/modules/imagefetcher/ZipUtil.scala
> +    while(zipStream.available() != 0) {
add space after `while`

2016-12-23 19:44 UTC, FunkySayu commented on backend/app/modules/imagefetcher/ZipUtil.scala
> +        val outputFile = new File(outputFolder + File.separator + filename)
move this after the comment, and remove the blank line

2016-12-23 19:44 UTC, FunkySayu commented on backend/app/modules/imagefetcher/ZipUtil.scala
> +        size = zipStream.read(buffer)
use `val size`, and remove the above `var size: Int = 0` definition.

2016-12-23 19:44 UTC, FunkySayu commented on backend/app/modules/imagefetcher/ZipUtil.scala
> +
remove blank line

2016-12-23 19:44 UTC, FunkySayu commented on backend/app/modules/imagefetcher/ZipUtil.scala
> +          case e: Throwable => println(e)
use `err` or `exception` instead of `e`. Much more explicit, even if it is understandable :)

2016-12-23 19:44 UTC, FunkySayu commented on backend/app/modules/imagefetcher/ZipUtil.scala
> +          case e: Throwable => println(e)
Shouldn't this be reported somewhere somehow ?

2016-12-23 19:44 UTC, FunkySayu commented on backend/app/modules/imagefetcher/ZipUtil.scala
> +}
Add blank line above

2016-12-23 19:47 UTC, FunkySayu requested changes
Some of my comments where outdated on the previous version (I forgot a commit, ups).

2016-12-23 19:47 UTC, FunkySayu commented on backend/app/modules/scheduler/SchedulerActor.scala
> +      .flatMap(details => fetcherActor.ask(FetchRGB("2015-01-01", details.place, Some(100), id)))
Is scale required here (Some(100))? Shouldn't we use the default scale?

2016-12-23 21:54 UTC, cassand commented on backend/app/modules/imagefetcher/FetcherActor.scala
> +      task.map(t => monitoring ! UpdateTask(processId, t.id, Some("Download started"), Some(20)))
This is the task progression, therefore starting download <=> 20%

2016-12-24 12:16 UTC, FunkySayu approved these changes

2016-12-24 12:20 UTC, FunkySayu commented
Nice job!

Generally speaking, avoid putting too much blank line in your code. This means less lines on the screen and it sometimes isn't useful / relevant to break the code.
On flow control statement (such as `while`, `if`...), you should avoid putting empty line right after, unless the statement is on several line (and in that specific case, you should refactor your code ;) ). Indentation is pretty meaningful about this.

This `Some(20)` is still a bit obscure, but I don't see anything else to do so...

2016-12-24 12:48 UTC, merged